STATUS_PENDING = 0
STATUS_ON_BOOK = 1
STATUS_DONE = 10
STATUS_MANUALLY_CANCELLED = 11
STATUS_AUTO_CANCELLED = 12
STATUS_PARTIALLY_FILLED = 13
STATUS_EXPIRED = 14  # Fixed orders only
STATUS_ERROR = 99
